export const TOGGLE_FAVORITE          = 'TOGGLE_FAVORITE'

export const FETCH_CATEGORIES_REQUEST   = 'FETCH_CATEGORIES_REQUEST'
export const FETCH_CATEGORIES_SUCCEEDED = 'FETCH_CATEGORIES_SUCCEEDED'
export const FETCH_CATEGORIES_FAILED    = 'FETCH_CATEGORIES_FAILED'

export const FETCH_PRODUCTS_CATEGORY_REQUEST   = 'FETCH_PRODUCTS_CATEGORY_REQUEST'
export const FETCH_PRODUCTS_CATEGORY_SUCCEEDED = 'FETCH_PRODUCTS_CATEGORY_SUCCEEDED'
export const FETCH_PRODUCTS_CATEGORY_FAILED    = 'FETCH_PRODUCTS_CATEGORY_FAILED'

export const FETCH_PRODUCT_REQUEST   = 'FETCH_PRODUCT_REQUEST'
export const FETCH_PRODUCT_SUCCEEDED = 'FETCH_PRODUCT_SUCCEEDED'
export const FETCH_PRODUCT_FAILED    = 'FETCH_PRODUCT_FAILED'
